### ISSUE TITLE
Shadowlands itemDB

### ISSUE THREAD

**Issue by Harshmage** [Xruptor/xanMortarPestle#11]
Updated itemDB.lua file in my fork with the new Shadowlands items.  6 herbs, 6 ores, 4 lockboxes (overcorrection by Blizzard from BFA, but missed the trend and didn't add a Revendreth lockbox or a junkbox).  Finally took the time to comment the rest of the items too.

https://github.com/Harshmage/xanMortarPestle/blob/master/itemDB.lua

**Comment by Xruptor** [comment]
Thank you very much for taking the time to update the itemDB.  I could update the file manually here on gitHub.  But it would be easier if you just push a Pull Request Commit and I can merge it with my code.  That way it's documented on GitHub as crediting you.  Otherwise I'd have to credit the file manually.  It doesn't bother me either way, just let me know what you would like to do 😄 Thanks again!

**Comment by Harshmage** [comment]
Submitted Pull Req, closing this issue
